### PR TITLE
Fix errors on regexes

### PR DESCRIPTION
**Pull request by Dreamsorcerer**
. Fix error caused by options pre-populating the option with None.
. Fix AttributeError caused by trying to call split() on a tuple.

### CODE REVIEW

**Comment by Dreamsorcerer** [comment]
The linting CI appears to be throwing an exception. Not sure that's got anything to do with my code changes...

**Comment by Dreamsorcerer** [comment]
It appears the same exception is present for the last commit on master, so not an issue I've introduced.

**Comment by decafjoe** [comment]
Hi, @Dreamsorcerer!

Thank you for the contribution. You're absolutely correct that your changes didn't break CI; that started failing on July 8th (along with all my other projects in Travis) and I haven't gotten around to fixing them.

I will figure out what's going on with that, get those fixes merged, get your changes merged, and cut a new release sometime this weekend.

How do you want to be credited in the changelog? By name or by GitHub handle or something else?

Thanks again for contributing!

**Comment by Dreamsorcerer** [comment]
Something like:
Sam Bull (Kopernio)

Thanks

**Comment by decafjoe** [comment]
I fixed the Travis issue, rebased your changes on the updated master, squashed them down to a [single commit](https://github.com/decafjoe/flake8-ownership/commit/199e8ff6906f5d063e73aefcc45c7658e13349b4), added a summary and attribution to [the changelog](https://flake8-ownership.readthedocs.io/en/2.0.1/changelog.html), cut the [2.0.1 release](https://pypi.org/project/flake8-ownership/2.0.1/), updated one of my test environments, and checked that everything worked (it appears to).

Sorry for the git weirdness but it was the easiest path forward (that I could see) that didn't require any effort on your end. The Travis fix was merged in PR #13 and your changes in PR #14.

Thanks again for your contribution, and feel free to reach out to me via email (see the git log) if you have any issues with the updated package!

**Pull request closed without merging**
